name: sync-and-merge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Sync fork
        run: gh repo sync ${{ github.repository }} --branch ${{ github.ref_name }} --source speedyapply/2025-SWE-College-Jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull updates locally
        run: git pull origin ${{ github.ref_name }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Update tracking file
        run: python merge_tracking.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add my-tracking.md
          git commit -m "Auto-update my-tracking.md with latest jobs and preserved statuses" || echo "No changes to commit"
          git push
